services:
    eliza:
        command: ["pnpm", "start", "--character=./characters/bizzy.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - ANTHROPIC_API_KEY=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
            - MONGODB_CONNECTION_STRING="mongodb+srv://kobosildaniel:INoQzGk25u7d9NpW@cluster0.ujtrf.mongodb.net/?retryWrites=true&w=majority"             #mongodb connection string
            - MONGODB_DATABASE="cluster0" 
        ports:
            - "3000:3000"
        restart: always
